name: Publish
on:
  push:
    branches: ["master"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install dependencies
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        run: npm ci

      - name: Build
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        run: npm run build

      - name: Test
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        run: npm test

      - name: Report coverage
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: codecov/codecov-action@master
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Bump version
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: "smockle/version-action@master"
        env:
          GITHUB_USER_EMAIL: bot@smockle.com
          GITHUB_USER_NAME: smockle-bot
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Publish
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: "actions/npm@master"
        with:
          args: "publish --access public"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
