name: Test
on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    steps:
      - name: Get sources
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm ci

      - name: Build (Non-Windows)
        if: matrix.os == 'ubuntu-latest'
        run: npm run build

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run build:windows

      - name: Test
        run: npm test

      - name: Report coverage (Non-Windows)
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@master
        with:
          token: ${{secrets.CODECOV_TOKEN}}
